[workspace]
members = ["crates/readable_core", "crates/readable_wasm"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[package]
name = "readability-cli"
version = "0.10.0"
edition.workspace = true
description = "A CLI to extract main content from HTML using logistic regression"

[[bin]]
name = "rdbl"
path = "src/main.rs"

[dependencies]
readable_core = { path = "crates/readable_core" }

# Command line argument parsing
clap = { version = "4.5", features = ["derive", "wrap_help", "env"] }

# Fetch the webpage
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }

# Async runtime
tokio = { version = "1.45", features = ["rt-multi-thread", "macros"] }

# Error handling and JSON output
anyhow = "1.0"
serde_json = "1.0"

[profile.dev]
debug = 0

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
