[workspace]
members = ["crates/rdbl_core", "crates/rdbl_wasm", "crates/rdbl_cli"]
default-members = ["crates/rdbl_cli"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
# Internal crates
rdbl_core = { version = "0.1.0", path = "crates/rdbl_core" }

# HTML parsing
html5ever = "0.27"
markup5ever_rcdom = "0.3"

# Encoding detection and conversion
encoding_rs = "0.8"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Lazy initialization
lazy_static = "1.5"

# WASM
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
js-sys = "0.3"

# CLI
clap = { version = "4.5", features = ["derive", "wrap_help", "env"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.45", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"
html2md = "0.2"

# Dev dependencies
pretty_assertions = "1.4"
wasm-bindgen-test = "0.3"

[profile.dev]
debug = 0

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
